/*
 *  Password retrieval pop-up promting for security question answer.
 *  @author Heather N. Larsen
 *  @version    1.0    2018/09/15:20:08
 */
public class SecurityQuestionGUI extends javax.swing.JPanel {

    /**
     * Creates new form SecurityQuestionGUI
     */
    public SecurityQuestionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        accountRetrieval = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        securityQuestion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();

        logo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heartbleed.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(341, 413));
        logo.setMinimumSize(new java.awt.Dimension(341, 413));

        accountRetrieval.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountRetrieval.setText("Heartbleed Account Retrieval");

        jScrollPane4.setBorder(null);

        securityQuestion.setEditable(false);
        securityQuestion.setBackground(new java.awt.Color(230, 230, 230));
        securityQuestion.setColumns(100);
        securityQuestion.setFont(new java.awt.Font("Calibri", 3, 16)); // NOI18N
        securityQuestion.setLineWrap(true);
        securityQuestion.setRows(2);
        securityQuestion.setText("SQ");
        securityQuestion.setWrapStyleWord(true);
        securityQuestion.setAutoscrolls(false);
        securityQuestion.setBorder(javax.swing.BorderFactory.createTitledBorder("Security Question"));
        securityQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        securityQuestion.setOpaque(false);
        jScrollPane4.setViewportView(securityQuestion);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(1);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer"));
        jScrollPane1.setViewportView(jTextArea1);

        nextButton.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accountRetrieval))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nextButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountRetrieval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountRetrieval;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextArea securityQuestion;
    // End of variables declaration//GEN-END:variables
}
