import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.naming.NameNotFoundException;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
/*
 *  The sign-up popup for the website.
 *  @author Heather N. Larsen
 *  @version    2.0     2018/09/15:22:40
 */
public class SignUpGUI extends javax.swing.JPanel {
    /**
     * Creates new form SignUpGUI
     */
    public SignUpGUI() throws IOException {
        initComponents();
        initMore();
        
        this.setVisible(true);
    }

    /**
     *  Retrieve more initialization details.
     *  @throws IOException 
     */
    private void initMore() throws IOException {
        RetrievalSystem rs = new RetrievalSystem();
        
        SQ1.setBackground(Color.WHITE);
        SQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            rs.sQ1, rs.sQ2, rs.sQ3, rs.sQ4, rs.sQ5, rs.sQ6, rs.sQ7, rs.sQ8,
            rs.sQ9, rs.sQ10, rs.sQ11
        }));
        
        SQ2.setBackground(Color.WHITE);
        SQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            rs.sQ12, rs.sQ13, rs.sQ14, rs.sQ15, rs.sQ16, rs.sQ17, rs.sQ18, rs.sQ19,
            rs.sQ20, rs.sQ21, rs.sQ22
        }));
    }/*****************************INIT.MORE************************************/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccount = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        getConfirmPassword = new javax.swing.JPasswordField();
        getPassword = new javax.swing.JPasswordField();
        getEmail = new javax.swing.JTextField();
        getPhone = new javax.swing.JFormattedTextField();
        ToSCheckBox = new javax.swing.JCheckBox();
        signUpButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorMessage = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        passConstraints = new javax.swing.JTextArea();
        SQ1 = new javax.swing.JComboBox<>();
        SQ1A = new javax.swing.JTextField();
        SQ2 = new javax.swing.JComboBox<>();
        SQ2A = new javax.swing.JTextField();
        Sig = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ToSAgreement = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(230, 230, 230));

        createAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createAccount.setText("Create Your Heartbleed Account");

        logo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heartbleed.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(341, 413));
        logo.setMinimumSize(new java.awt.Dimension(341, 413));

        getUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        getUsername.setSelectionColor(new java.awt.Color(204, 0, 0));
        getUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUsernameActionPerformed(evt);
            }
        });

        getConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getConfirmPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirm Password"));
        getConfirmPassword.setSelectionColor(new java.awt.Color(204, 0, 0));

        getPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        getPassword.setSelectionColor(new java.awt.Color(204, 0, 0));
        getPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPasswordActionPerformed(evt);
            }
        });

        getEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        getEmail.setSelectionColor(new java.awt.Color(204, 0, 0));
        getEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmailActionPerformed(evt);
            }
        });

        getPhone.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone (Optional)"));
        try {
            getPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getPhone.setSelectionColor(new java.awt.Color(204, 0, 0));
        getPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPhoneActionPerformed(evt);
            }
        });

        ToSCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToSCheckBoxActionPerformed(evt);
            }
        });

        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        errorMessage.setEditable(false);
        errorMessage.setBackground(new java.awt.Color(230, 230, 230));
        errorMessage.setColumns(100);
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setLineWrap(true);
        errorMessage.setRows(2);
        errorMessage.setWrapStyleWord(true);
        errorMessage.setAutoscrolls(false);
        errorMessage.setBorder(null);
        errorMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(errorMessage);

        jScrollPane4.setBorder(null);

        passConstraints.setEditable(false);
        passConstraints.setBackground(new java.awt.Color(230, 230, 230));
        passConstraints.setColumns(100);
        passConstraints.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        passConstraints.setLineWrap(true);
        passConstraints.setRows(2);
        passConstraints.setText("Passwords must be 8-16 characters long and contain:\n             1   uppercase  character           1   lowercase  character\n             1   special  character                1   digit");
        passConstraints.setWrapStyleWord(true);
        passConstraints.setAutoscrolls(false);
        passConstraints.setBorder(null);
        passConstraints.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(passConstraints);

        SQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SQ1.setBorder(javax.swing.BorderFactory.createTitledBorder("Security Question 1"));

        SQ1A.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer"));
        SQ1A.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        SQ1A.setSelectionColor(new java.awt.Color(204, 0, 0));

        SQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SQ2.setBorder(javax.swing.BorderFactory.createTitledBorder("Security Question 2"));

        SQ2A.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer"));
        SQ2A.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        SQ2A.setSelectionColor(new java.awt.Color(204, 0, 0));

        Sig.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sig.setText("Heartbleed");

        ToSAgreement.setColumns(1);
        ToSAgreement.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        ToSAgreement.setLineWrap(true);
        ToSAgreement.setRows(2);
        ToSAgreement.setText("Check here to indicate that you have read and agree to the Terms of Service.");
        ToSAgreement.setWrapStyleWord(true);
        ToSAgreement.setAutoscrolls(false);
        ToSAgreement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(224, 224, 224)));
        jScrollPane1.setViewportView(ToSAgreement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SQ1A, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SQ2A, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAccount)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sig)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ToSCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(signUpButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sig, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createAccount))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(SQ1A, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SQ2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToSCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(signUpButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUsernameActionPerformed

    }//GEN-LAST:event_getUsernameActionPerformed

    private void getEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmailActionPerformed

    }//GEN-LAST:event_getEmailActionPerformed

    private void getPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPhoneActionPerformed

    }//GEN-LAST:event_getPhoneActionPerformed

    private void getPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPasswordActionPerformed

    }//GEN-LAST:event_getPasswordActionPerformed

    private void ToSCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToSCheckBoxActionPerformed

    }//GEN-LAST:event_ToSCheckBoxActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        try {
            errorMessage.setText("");
            UserDatabase db = new UserDatabase();
            
            String select1 = SQ1.getSelectedItem().toString();
            String answer1 = SQ1A.getText();
            String select2 = SQ2.getSelectedItem().toString();
            String answer2 = SQ2A.getText();
            
            try {
                if(checkUsername() && checkEmail() && checkPassword() && checkSQ() && checkBox()) {
                    String phone = null;
                    if(!getPhone.getText().contains(" ")) {
                        phone = getPhone.getText();
                    }
                    
                    db.registerUser(getUsername.getText(), getPassword.getText(),
                            getEmail.getText(), select1, answer1, select2, answer2, phone);
                    
                    SwingUtilities.getWindowAncestor(this).dispose();
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NameNotFoundException ex) {
                Logger.getLogger(SignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IllegalArgumentException iae) {
            errorMessage.setText(iae.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(SignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    /**
     *  Checks if the password and confirmed password match.
     *  @return true if both password fields match and not null
     */
    private boolean checkPassword() {
        String password = getPassword.getText();
        
        if(password.compareTo("") == 0) {
            errorMessage.setText("Please enter a password.");
            return false;
        }
        else if(password.compareTo(getConfirmPassword.getText()) == 0) {
            //Password must be min of 8 characters max of 16
            if((8 > password.length()) || (
                    password.length() > 16)) {
                errorMessage.setText("Password must be 8-16 characters long.");
                return false;
            }
            
            boolean upperFlag = false;
            boolean lowerFlag = false;
            boolean numFlag   = false;
            boolean charFlag  = false;
            
            for(int i = 0; i < password.length(); ++i) {
                String sp = "/*!@#$%^&*()\\\"{}_[]|\\\\?/<>,.";
                char ch = password.charAt(i);
                
                if(Character.isUpperCase(ch))             { upperFlag = true; }
                if(Character.isLowerCase(ch))             { lowerFlag = true; }
                if(Character.isDigit(ch))                 { numFlag   = true; }
                if(sp.contains(password.substring(i, i))) { charFlag  = true; }
            }      
            //Password must contain 1 uppercase letter
            if(!upperFlag) {
                errorMessage.setText("Password must contain at least one uppercase letter.");
                return false;
            }
            //Password must contain 1 lowercase letter
            if(!lowerFlag) {
                errorMessage.setText("Password must contain at least one lowercase letter.");
                return false;
            }
            //Password must contain 1 number
            if(!numFlag) {
                errorMessage.setText("Password must contain at least one digit.");
                return false;
            }
            //Password must contain 1 special character
            if(!charFlag) {
                errorMessage.setText("Password must contain at least one special character.");
                return false;
            }
            return true;
        }
        else {
            errorMessage.setText("The entered passwords do not match.");
            return false; 
        }
    }/******************************CHECK.PASSWORD******************************/
    /**
     *  Checks if a username has been entered into the registration field.
     *  @return true if username entered
     */
    private boolean checkUsername() {
        if(getUsername.getText().compareTo("") != 0) { return true; }
        else {
            errorMessage.setText("Please enter a username.");
            return false;
        }
    }/******************************CHECK.USERNAME******************************/
    /**
     *  Checks if an email has been entered and if it is valid.
     *  @return true if email is valid and not already registered
     */
    private boolean checkEmail() throws IOException, FileNotFoundException, NameNotFoundException {
        String email = getEmail.getText();
        
        if(email.contains("@")) { 
            UserDatabase db = new UserDatabase();
            
            if(db.emailExists(email)) {
                errorMessage.setText("This email address has already been registered.");
                return false;
            }
            
            return true;
        }
        else {
            errorMessage.setText("Please enter a valid email. This email will be "+
                    "used for verification and account retrieval.");
            return false;
        }
    }/******************************CHECK.EMAIL*********************************/
    /**
     *  Checks if the security question fields have been filled.
     *  @return true if satisfied
     */
    private boolean checkSQ() {
        if(SQ1A.getText().compareTo("") == 0) {
            errorMessage.setText("Please enter an answer for Security Question 1.");
            return false;
        }
        if(SQ2A.getText().compareTo("") == 0) {
            errorMessage.setText("Please enter an answer for Security Question 2.");
            return false;
        }
        
        return true;
    }/********************************CHECK.SQ**********************************/
    /**
     *  Checks if the user agreed to the ToS via the checkbox.
     *  @return true if checked
     */
    private boolean checkBox() {
        if(ToSCheckBox.isSelected()) { return true; }
        else {
            errorMessage.setText("Please check that you have read and agree to " +
                    "the Terms of Service agreement.");
            return false;
        }
    }/**********************************CHECK.BOX*******************************/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SQ1;
    private javax.swing.JTextField SQ1A;
    private javax.swing.JComboBox<String> SQ2;
    private javax.swing.JTextField SQ2A;
    private javax.swing.JLabel Sig;
    private javax.swing.JTextArea ToSAgreement;
    private javax.swing.JCheckBox ToSCheckBox;
    private javax.swing.JLabel createAccount;
    private javax.swing.JTextArea errorMessage;
    private javax.swing.JPasswordField getConfirmPassword;
    private javax.swing.JTextField getEmail;
    private javax.swing.JPasswordField getPassword;
    private javax.swing.JFormattedTextField getPhone;
    private javax.swing.JTextField getUsername;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea passConstraints;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}/********************************SIGN.UP.GUI_CLASS*****************************/